// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// By considering the terms in the Fibonacci sequence whose values do not exceed N,
// find the sum of the even-valued terms.

// BRUTEFORCE: Iterate through all the numbers and check if the sum is even, and then add to the sum. Very, Very Long.
// Even the recursion i use is wayy too long.

// #include <iostream>
// using namespace std;
// // BETTERFORCE: Use all the terms that appear in intervals of three after the first even number appearance.
// long Fibonacci(long n)
// {
//     if (n == 1)
//         return 1;
//     else if (n == 2)
//         return 2;
//     else
//         return Fibonacci(n - 1) + Fibonacci(n - 2);
// }
// long long Even_Sum(long limit)
// {
//     int sum = 0;
//     for (int i = 2; Fibonacci(i) < limit; i += 3)
//     {
//         sum += Fibonacci(i);
//     }
//     return sum;
// }
// int main()
// {
//     long limit;
//     cin >> limit;
//     cout << Even_Sum(limit);
//     return 0;
// }

// Optimal Approach: Without recursion and just Direct loops.
#include <iostream>
using namespace std;

int main()
{
    long long n;
    cin >> n;
    long long a = 2, b = 8, sum;
    if (n < 2)
    {
        sum = 0;
    }
    else if (n >= 2 && n < 8)
    {
        sum = 2;
    }
    else
    {
        sum = 10;
        long long c = 4 * b + a;
        while (c < n)
        {
            sum += c;
            a = b;
            b = c;
            c = 4 * b + a;
        }
    }
    cout << sum << endl;
    return 0;
}